version: '3.8'

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: sail
      DB_PASSWORD: password
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - app

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - laravel
    networks:
      - app

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: laravel
    networks:
    - app

networks:
  app:
    driver: bridge